package subway.domain;

import javax.persistence.*;
import java.util.Objects;

/**
 * create table station (
 *     id bigint generated by default as identity,
 *     name varchar(255) not null,
 *     primary key (id)
 * )
 */
@Table(name = "station")
@Entity
public class Station {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Column(name = "name", nullable = false)
	private String name;

	@ManyToOne
	@JoinColumn(name = "line_id")
	private Line line;


	protected Station(){
		// empty
	}

	public Station(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public long getId() {
		return this.id;
	}

	public void changeName(String name) {
		this.name = name;
	}

//	public void setLine(Line line){
//		this.line = line;
//		line.addStation(this);
//	}

	public void setLine(Line line) {
		if (Objects.nonNull(this.line)) {
			this.line.getStations().remove(this);
		}
		this.line = line;
		line.getStations().add(this);
	}

	public Line getLine() {
		return this.line;
	}
}
